# product-catalog-service (port 9003). Domain service.
serviceName: product-catalog-service
containerPort: 9003
service:
  port: 9003

image:
  tag: latest

config:
  CONFIG_SERVER_URI: http://config-server:8888
  CONFIG_SERVER_USER: config
  SPRING_PROFILES_ACTIVE: dev,docker
  EUREKA_USERNAME: eureka

secrets:
  CONFIG_SERVER_PASSWORD: config
  EUREKA_PASSWORD: eureka
  REDIS_PASSWORD: telco
