# ticket-service (port 9010). Domain service.
serviceName: ticket-service
containerPort: 9010
service:
  port: 9010

image:
  tag: latest

config:
  CONFIG_SERVER_URI: http://config-server:8888
  CONFIG_SERVER_USER: config
  SPRING_PROFILES_ACTIVE: dev,docker
  EUREKA_USERNAME: eureka

secrets:
  CONFIG_SERVER_PASSWORD: config
  EUREKA_PASSWORD: eureka
  REDIS_PASSWORD: telco
